import type { Zone } from '@/types';

/**
 * The Road: 66 zones from the Slums of Nafs to the Throne of Iblis.
 * `base_hp` is the authored HP of the zone's first monster; the scaling
 * curve in `monsters.ts` derives everything else from the zone id.
 */
export const ZONES: Zone[] = [
  {
    id: 1,
    name: 'The Slums of Nafs',
    theme: 'Laziness, small sins',
    boss_name: 'Gluttony Hound',
    base_hp: 50,
    lore: 'Where every soul first wakes. The whispers are soft here, but constant.',
  },
  {
    id: 2,
    name: 'The Desert of Delay',
    theme: 'Procrastination',
    boss_name: 'The Slack King',
    base_hp: 58,
    lore: 'A burning plain where tomorrow never comes.',
  },
  {
    id: 3,
    name: 'The Valley of Whispers',
    theme: 'Waswas',
    boss_name: 'Whisper Warlock',
    base_hp: 66,
    lore: 'Every stone speaks. Every voice doubts.',
  },
  {
    id: 4,
    name: 'The Fortress of Arrogance',
    theme: 'Pride, ego',
    boss_name: 'The Proud General',
    base_hp: 76,
    lore: 'Its walls are made of self-praise.',
  },
  {
    id: 5,
    name: 'The Sea of Distraction',
    theme: 'Social media, phones',
    boss_name: 'The Endless Feeder',
    base_hp: 88,
    lore: 'An infinite scroll of black water.',
  },
  {
    id: 6,
    name: 'The Cave of Sleep',
    theme: 'Oversleeping',
    boss_name: 'The Lethargy Beast',
    base_hp: 101,
    lore: 'The sun rises outside. You do not.',
  },
  {
    id: 7,
    name: 'The Bazaar of Greed',
    theme: 'Money, materialism',
    boss_name: 'The Golden Serpent',
    base_hp: 116,
    lore: 'Everything is for sale. Including you.',
  },
  {
    id: 8,
    name: 'The Arena of Anger',
    theme: 'Rage, temper',
    boss_name: 'The Fury Titan',
    base_hp: 133,
    lore: 'Blood on the sand. Fury in the heart.',
  },
  {
    id: 9,
    name: 'The Garden of Lust',
    theme: 'Lower desires',
    boss_name: 'The Nafs Serpent',
    base_hp: 153,
    lore: 'Beautiful. Poisonous. Yours.',
  },
  {
    id: 10,
    name: 'The Library of Doubt',
    theme: 'Weak iman',
    boss_name: 'The Doubt Djinn',
    base_hp: 176,
    lore: 'Every book contradicts the next.',
  },
  {
    id: 11,
    name: 'The Mountain of Hardship',
    theme: 'Trials',
    boss_name: 'The Suffering Giant',
    base_hp: 202,
    lore: 'Every step uphill. No summit visible.',
  },
  {
    id: 12,
    name: 'The River of Regret',
    theme: 'Past sins',
    boss_name: 'The Guilt Wraith',
    base_hp: 233,
    lore: 'It flows backward. Always backward.',
  },
  {
    id: 13,
    name: 'The Forest of Envy',
    theme: 'Hasad',
    boss_name: 'The Green-Eyed Shade',
    base_hp: 268,
    lore: 'Every tree bears fruit you cannot reach.',
  },
  {
    id: 14,
    name: 'The Tower of Show-Off',
    theme: 'Riya',
    boss_name: 'The Two-Faced Lord',
    base_hp: 308,
    lore: 'Mirrors on every wall.',
  },
  {
    id: 15,
    name: 'The Pit of Despair',
    theme: 'Hopelessness',
    boss_name: 'The Despair Fiend',
    base_hp: 354,
    lore: 'The bottom is deeper than you think.',
  },
  {
    id: 16,
    name: 'The Hall of Gossip',
    theme: 'Ghiba',
    boss_name: 'The Forked-Tongue Demon',
    base_hp: 407,
    lore: 'Whispers about everyone but you.',
  },
  {
    id: 17,
    name: 'The Chamber of Secrets',
    theme: 'Hidden sins',
    boss_name: 'The Shadow Spy',
    base_hp: 468,
    lore: 'Your own heart, exposed.',
  },
  {
    id: 18,
    name: 'The Forge of Power Lust',
    theme: 'Tyranny',
    boss_name: 'The Iron Tyrant',
    base_hp: 539,
    lore: 'Where kings are made and broken.',
  },
  {
    id: 19,
    name: 'The Swamp of Sloth',
    theme: 'Deep laziness',
    boss_name: 'The Bog Beast',
    base_hp: 620,
    lore: 'Every step sinks.',
  },
  {
    id: 20,
    name: 'The Cliffs of Fear',
    theme: 'Anxiety',
    boss_name: 'The Terror Hawk',
    base_hp: 713,
    lore: 'One wrong step. One long fall.',
  },
  {
    id: 21,
    name: 'The Desert of Thirst',
    theme: 'Spiritual dryness',
    boss_name: 'The Bone Dry Djinn',
    base_hp: 820,
    lore: 'No water for miles. No dhikr for days.',
  },
  {
    id: 22,
    name: 'The Labyrinth of Confusion',
    theme: 'Misguidance',
    boss_name: 'The Mind Bender',
    base_hp: 943,
    lore: 'Every path leads back.',
  },
  {
    id: 23,
    name: 'The Court of Injustice',
    theme: 'Oppression',
    boss_name: 'The Unjust Vizier',
    base_hp: 1084,
    lore: 'The verdict is already written.',
  },
  {
    id: 24,
    name: 'The Fire of Hatred',
    theme: 'Grudges',
    boss_name: 'The Burning Khan',
    base_hp: 1247,
    lore: 'Old flames never die here.',
  },
  {
    id: 25,
    name: 'The Mirror of Vanity',
    theme: 'Vanity',
    boss_name: 'The Glass Demon',
    base_hp: 1434,
    lore: 'You love what you see. That is the trap.',
  },
  {
    id: 26,
    name: 'The Vault of Addiction',
    theme: 'Drugs, porn, gambling',
    boss_name: 'The Chain Master',
    base_hp: 1649,
    lore: "The chains are gold. That's the trick.",
  },
  {
    id: 27,
    name: 'The Hive of Distraction',
    theme: 'Endless scrolling',
    boss_name: 'The Swarm Queen',
    base_hp: 1896,
    lore: 'A million notifications. None important.',
  },
  {
    id: 28,
    name: 'The Stage of Fame',
    theme: 'Seeking fame',
    boss_name: 'The Masked Idol',
    base_hp: 2180,
    lore: 'Applause fades. The mask stays.',
  },
  {
    id: 29,
    name: 'The Den of Betrayal',
    theme: 'Dishonesty',
    boss_name: 'The Oath Breaker',
    base_hp: 2507,
    lore: 'Every promise here was a lie.',
  },
  {
    id: 30,
    name: 'The Well of Whisperers',
    theme: 'Deep waswas',
    boss_name: 'The Whispering Well',
    base_hp: 2883,
    lore: 'Look down. It looks back.',
  },
  {
    id: 31,
    name: 'The Battlefield of Excuses',
    theme: '"Tomorrow"',
    boss_name: 'The Tomorrow Titan',
    base_hp: 3315,
    lore: 'Bones of every good intention.',
  },
  {
    id: 32,
    name: 'The Crypt of Dead Hearts',
    theme: 'Hard hearts',
    boss_name: 'The Ashen King',
    base_hp: 3812,
    lore: 'Where feeling goes to die.',
  },
  {
    id: 33,
    name: 'The Wasteland of Waste',
    theme: 'Time-wasting',
    boss_name: 'The Hour Eater',
    base_hp: 4384,
    lore: 'You had 24 hours. It took all of them.',
  },
  {
    id: 34,
    name: 'The Chasm of Separation',
    theme: 'Broken ties',
    boss_name: 'The Severer',
    base_hp: 5042,
    lore: 'Family on one side. You on the other.',
  },
  {
    id: 35,
    name: 'The Temple of False Gods',
    theme: 'Shirk-adjacent',
    boss_name: 'The Idol Colossus',
    base_hp: 5798,
    lore: 'You built it yourself.',
  },
  {
    id: 36,
    name: 'The Cage of Comfort',
    theme: 'Comfort zone',
    boss_name: 'The Soft Jailer',
    base_hp: 6668,
    lore: 'The bars are made of pillows.',
  },
  {
    id: 37,
    name: 'The Storm of Panic',
    theme: 'Overwhelm',
    boss_name: 'The Chaos Djinn',
    base_hp: 7668,
    lore: 'Every direction is the wrong one.',
  },
  {
    id: 38,
    name: 'The Frost of Cold Hearts',
    theme: 'Apathy',
    boss_name: 'The Ice Sheikh',
    base_hp: 8818,
    lore: 'You stopped caring. That was the point.',
  },
  {
    id: 39,
    name: 'The Web of Lies',
    theme: 'Deception',
    boss_name: 'The Weaver',
    base_hp: 10141,
    lore: 'The first lie was yours.',
  },
  {
    id: 40,
    name: 'The Pit of Arrogance',
    theme: 'Deep pride',
    boss_name: 'The Fallen Prince',
    base_hp: 11662,
    lore: 'Look how far you have fallen. And still proud.',
  },
  {
    id: 41,
    name: 'The Fort of Stubbornness',
    theme: 'Refusing advice',
    boss_name: 'The Iron Skull',
    base_hp: 13411,
    lore: 'You know better than everyone. Everyone.',
  },
  {
    id: 42,
    name: 'The Sea of Doubts',
    theme: 'Disbelief',
    boss_name: 'The Wave Wraith',
    base_hp: 15423,
    lore: "Every wave is a question you can't answer.",
  },
  {
    id: 43,
    name: 'The Hall of Mirrors',
    theme: 'Self-deception',
    boss_name: 'The Illusion Master',
    base_hp: 17736,
    lore: 'Which one is really you?',
  },
  {
    id: 44,
    name: 'The Forge of Anger',
    theme: 'Deep rage',
    boss_name: 'The Rage Smith',
    base_hp: 20396,
    lore: 'He hammers grudges into weapons.',
  },
  {
    id: 45,
    name: 'The Nest of Backbiters',
    theme: 'Ghiba fortress',
    boss_name: 'The Tongue Collector',
    base_hp: 23456,
    lore: 'He keeps every word you said.',
  },
  {
    id: 46,
    name: 'The Maze of Waswas',
    theme: 'Endless whispers',
    boss_name: 'The Echo Demon',
    base_hp: 26974,
    lore: 'Your own voice, mocking you.',
  },
  {
    id: 47,
    name: 'The Throne of Dunya',
    theme: 'Worldly love',
    boss_name: 'The Dunya Queen',
    base_hp: 31020,
    lore: 'She is beautiful and she is leaving.',
  },
  {
    id: 48,
    name: 'The Chasm of Kibr',
    theme: 'Grand arrogance',
    boss_name: 'The Kibr Behemoth',
    base_hp: 35673,
    lore: 'He grows with every praise you accept.',
  },
  {
    id: 49,
    name: 'The Tomb of Hearts',
    theme: 'Spiritual death',
    boss_name: 'The Grave Warden',
    base_hp: 41024,
    lore: 'Your heart is buried here. Find it.',
  },
  {
    id: 50,
    name: 'The Forest of Fitnah',
    theme: 'Tribulation',
    boss_name: 'The Fitnah Beast',
    base_hp: 47178,
    lore: 'Every branch is a test.',
  },
  {
    id: 51,
    name: 'The Storm of Nafs',
    theme: 'Inner battle',
    boss_name: 'The Nafs Tempest',
    base_hp: 54255,
    lore: 'The storm is not outside. It never was.',
  },
  {
    id: 52,
    name: 'The Cave of Riya',
    theme: 'Hidden shirk',
    boss_name: 'The Silent Showman',
    base_hp: 62393,
    lore: "Nobody is watching. That's the test.",
  },
  {
    id: 53,
    name: 'The Arena of Ego',
    theme: 'Self-worship',
    boss_name: 'The Ego Champion',
    base_hp: 71752,
    lore: 'The crowd is you. The judge is you.',
  },
  {
    id: 54,
    name: 'The Lake of Regret',
    theme: 'Sorrow',
    boss_name: 'The Weeping Djinn',
    base_hp: 82515,
    lore: "Every tear you didn't cry is here.",
  },
  {
    id: 55,
    name: 'The Forge of Whispers',
    theme: 'Shaytan forge',
    boss_name: 'The Whisper Smith',
    base_hp: 94892,
    lore: 'This is where doubts are made.',
  },
  {
    id: 56,
    name: 'The Bridge of No Return',
    theme: 'Point of no return',
    boss_name: 'The Bridge Keeper',
    base_hp: 109126,
    lore: "Cross. Don't look back.",
  },
  {
    id: 57,
    name: 'The Army of Iblis',
    theme: 'First soldiers',
    boss_name: 'The Vanguard General',
    base_hp: 125495,
    lore: 'They are not like the ones before.',
  },
  {
    id: 58,
    name: 'The Fortress of Smoke',
    theme: 'Deception HQ',
    boss_name: 'The Smoke Lord',
    base_hp: 144319,
    lore: 'It looks like everything you ever wanted.',
  },
  {
    id: 59,
    name: 'The Throne Room of Waswas',
    theme: 'Whisper HQ',
    boss_name: 'The Grand Whisperer',
    base_hp: 165967,
    lore: 'The whisper is now a roar.',
  },
  {
    id: 60,
    name: 'The Court of the Fallen',
    theme: 'Fallen jinn',
    boss_name: 'The Fallen Vizier',
    base_hp: 190862,
    lore: 'They fell. They remember falling.',
  },
  {
    id: 61,
    name: 'The Fire of the Fallen',
    theme: 'Hellfire-adjacent',
    boss_name: 'The Flame Khan',
    base_hp: 219491,
    lore: "You feel the heat. That's not imagination.",
  },
  {
    id: 62,
    name: 'The Council of Shadows',
    theme: 'Iblis advisors',
    boss_name: 'The Shadow Council',
    base_hp: 252415,
    lore: 'Six voices. One agenda.',
  },
  {
    id: 63,
    name: 'The Gate of Iblis',
    theme: 'Final gate',
    boss_name: 'The Gate Warden',
    base_hp: 290277,
    lore: 'Beyond this: no return.',
  },
  {
    id: 64,
    name: 'The Plain of Final Battle',
    theme: 'Pre-final',
    boss_name: 'The Last General',
    base_hp: 333819,
    lore: 'Your ancestors fought here. So will you.',
  },
  {
    id: 65,
    name: 'The Throne Approach',
    theme: 'Iblis approach',
    boss_name: 'The Champion of Iblis',
    base_hp: 383892,
    lore: 'His greatest warrior. Your final test.',
  },
  {
    id: 66,
    name: 'The Throne of Iblis',
    theme: 'FINAL',
    boss_name: 'IBLIS',
    base_hp: 99999999999999999,
    lore: 'He has waited since the beginning of time. For you.',
  },
];

/** Map for O(1) lookups. */
const ZONE_BY_ID = new Map<number, Zone>(ZONES.map((z) => [z.id, z]));

export function getZone(id: number): Zone {
  const zone = ZONE_BY_ID.get(id);
  if (!zone) throw new Error(`Unknown zone: ${id}`);
  return zone;
}

export function isFinalZone(id: number): boolean {
  return id === 66;
}
